// src/components/Header/ColorSelect.tsx
import { last, range } from "lodash"
import { hsl } from "color"
import { useEffect } from "react"
import classNames from "classnames"
import { useSettings } from "~/state/Settings"
import { useUIState } from "~/state/UIState"

export function ColorSelect() {
  const toggle = useUIState(s => s.toggleColorSelectMode)

  const color = useSettings(s => s.color)
  const setColor = useSettings(s => s.setColor)

  useEffect(() => {
    // Defer adding eventListener, otherwise the initial click that opened this
    // Widget will immediately close it again.
    setTimeout(() => {
      document.addEventListener("click", toggle)
    }, 0)

    return () => document.removeEventListener("click", toggle)
  }, [])

  return (
    <div className="absolute top-2 -left-40 bg-slate-900 rounded flex flex-row p-2">
      {useColorCols().map((col, colIndex) => (
        <div key={colIndex} className="flex flex-col">
          {col.map(buttonColor => (
            <button
              key={buttonColor}
              className={classNames(
                "w-8 h-8 rounded-full m-1 border-2 border-transparent",
                buttonColor === color && "border-slate-300"
              )}
              style={{ backgroundColor: buttonColor }}
              onClick={() => setColor(buttonColor)}
            />
          ))}
        </div>
      ))}
    </div>
  )
}

function useColorCols() {
  const colorCols: string[][] = []

  colorCols.push([])
  for (const lightness of range(0, 100, 20)) {
    last(colorCols)!.push(hsl(0, 0, lightness).hex())
  }

  for (const hue of range(0, 360, 36)) {
    colorCols.push([])
    for (const lightness of range(20, 90, 15)) {
      last(colorCols)!.push(hsl(hue, 100, lightness).hex())
    }
  }

  return colorCols
}

// src/components/Header/ColorSelect.svelte
<script lang="ts">
  import { Color, ColorSelectMode } from '$stores'
  import { last, range } from 'lodash'
  import { onMount } from 'svelte'
  import { hsl } from 'color'

  const colorCols: string[][] = []

  colorCols.push([])
  for (const lightness of range(0, 100, 20)) {
    last(colorCols)!.push(hsl(0, 0, lightness).hex())
  }

  for (const hue of range(0, 360, 36)) {
    colorCols.push([])
    for (const lightness of range(20, 90, 15)) {
      last(colorCols)!.push(hsl(hue, 100, lightness).hex())
    }
  }

  onMount(() => {
    function onClick() {
      ColorSelectMode.set(false)
    }
    document.addEventListener('click', onClick)
    return () => document.removeEventListener('click', onClick)
  })
</script>

<div class="absolute top-2 -left-40 bg-slate-900 rounded flex flex-row p-2">
  {#each colorCols as col}
    <div class="flex flex-col">
      {#each col as color}
        <button
          class="w-8 h-8 rounded-full m-1 border-2 border-transparent"
          class:border-slate-300={$Color == color}
          style="background-color: {color}"
          on:click={() => Color.set(color)}
        />
      {/each}
    </div>
  {/each}
</div>
