// src/components/Header/ThicknessButton.svelte
<script lang="ts">
  import PolyLine from '$components/Paper/PolyLine.svelte'
  import ToolButton from '$components/Header/ToolButton.svelte'
  import { Thickness } from '$stores'

  export let thickness: number
</script>

<ToolButton active={thickness == $Thickness} on:click={() => Thickness.set(thickness)}>
  <svg class="w-full h-full" viewBox="0 0 100 100">
    <PolyLine
      thickness={thickness * 2}
      color="white"
      points={[
        [10, 10],
        [75, 25],
        [25, 50],
        [75, 90]
      ]}
    />
  </svg>
</ToolButton>

// src/components/Header/ThicknessButton.tsx
import { HeaderButton } from "~/components/Header/HeaderButton"
import { PolyLine } from "~/components/Paper/PolyLine"
import { useSettings } from "~/state/Settings"

export function ThicknessButton({ thickness }: { thickness: number }) {
  const activeThickness = useSettings(s => s.thickness)
  const setThickness = useSettings(s => s.setThickness)

  return (
    <HeaderButton
      active={thickness == activeThickness}
      onClick={() => setThickness(thickness)}
    >
      <svg className="w-full h-full" viewBox="0 0 100 100">
        <PolyLine
          thickness={thickness * 2}
          color="white"
          points={[
            [10, 10],
            [75, 25],
            [25, 50],
            [75, 90],
          ]}
        />
      </svg>
    </HeaderButton>
  )
}
